# Generated by Django 5.2.14 on 2026-05-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('blended_cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('minutes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destination')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('side', models.CharField(choices=[('buy', 'Buy (Supplier)'), ('sell', 'Sell (Customer)')], max_length=4)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.company')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('rate_per_minute', models.DecimalField(decimal_places=6, max_digits=10)),
                ('minimum_duration_sec', models.PositiveIntegerField(default=0)),
                ('billing_increment_sec', models.PositiveIntegerField(default=60)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.destination')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.tariff')),
            ],
            options={
                'ordering': ['prefix'],
                'unique_together': {('tariff', 'prefix', 'effective_date')},
            },
        ),
    ]
