# Generated by Django 5.2.14 on 2026-05-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=100)),
                ('ani', models.CharField(blank=True, max_length=30)),
                ('dnis', models.CharField(blank=True, max_length=30)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('answer_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('billed_duration_sec', models.PositiveIntegerField(default=0)),
                ('buy_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('buy_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sell_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('disconnect_cause', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdr_as_customer', to='core.company')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.destination')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdr_as_supplier', to='core.company')),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.switch')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'customer'], name='qos_cdr_start_t_227407_idx'), models.Index(fields=['start_time', 'supplier'], name='qos_cdr_start_t_ee1849_idx')],
            },
        ),
        migrations.CreateModel(
            name='MinuteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('side', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=8)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('connected_calls', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('asr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('acd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.destination')),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.switch')),
            ],
            options={
                'ordering': ['-hour'],
                'unique_together': {('hour', 'switch', 'company', 'destination', 'side')},
            },
        ),
    ]
